# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
  app_version("1.0.0")
  copyright("#{Time.now.year} Stromkreis")
  overwrite_screenshots("true")
