# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
# The app version comes from Version.xcconfig via the release lane.
  copyright("#{Time.now.year} Stromkreis")
  overwrite_screenshots("true")
